# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  N = 3

  (1..N).each do |machine_id|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "debian/jessie64"
    # vagrant plugin install vagrant-hostmanager
    config.hostmanager.enabled = true
    # vagrant plugin install vagrant-vbguest
    config.vbguest.auto_update = false
    config.vm.define "node#{machine_id}" do |machine|
      machine.vm.hostname = "node#{machine_id}"
      config.vm.provider :virtualbox do |vb|
	vb.name	= "node#{machine_id}"
	vb.customize ["modifyvm", :id, "--memory", "4096"]
      end
      machine.vm.network "private_network", ip: "192.168.38.#{10+machine_id}"
      # Updating /etc/hosts file on active guest machines...
      config.vm.provision :hostmanager
      # Provision with Shell Script
      machine.vm.provision :shell do |shell|
	shell.path = "provision.sh"
      end
    end
  end
end
