# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  vmbox = "puppetlab-centos-64-nocm"
  vmboxurl = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"

  config.vm.define :node1 do |node1|

    node1.vm.box = vmbox
    node1.vm.box_url = vmboxurl

    node1.vm.network :private_network, ip: "192.168.90.11"
    node1.vm.hostname = "node1"

    node1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
    end

    node1.vm.provision :shell do |shell|
      shell.path = "provision.sh"
    end

  end

end
