#!/bin/bash
## install cloudera manager repository ( from /mnt or internet )
if [ -f /mnt/repodata/repomd.xml ]; then
  cat > /etc/yum.repos.d/local.repo << EOF
[local]
name=local
baseurl=file:///mnt
gpgkey=
enabled=1
gpgcheck=0
EOF
else
  wget http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/cloudera-manager.repo -O /etc/yum.repos.d/cloudera-manager.repo
fi
## install required packages
yum -y install epel-release wget tar gzip ntp openssh-clients openssh-server
yum -y install oracle-j2sdk1.7 cloudera-manager-agent cloudera-manager-server-db-2 cloudera-manager-server
## configure JDK 1.7 provided by Cloudera
ln -s /usr/java/jdk1.7.0_67-cloudera /usr/java/default
## configure alternatives for java
update-alternatives --install /usr/bin/java  java  /usr/java/default/bin/java  16001 \
            --slave /usr/lib/jvm/jre jre /usr/java/default/jre \
            --slave /usr/lib/jvm-exports/jre jre_exports /usr/java/default/jre \
            --slave /usr/bin/keytool keytool /usr/java/default/jre/bin/keytool \
            --slave /usr/bin/orbd orbd /usr/java/default/jre/bin/orbd \
            --slave /usr/bin/pack200 pack200 /usr/java/default/jre/bin/pack200 \
            --slave /usr/bin/rmid rmid /usr/java/default/jre/bin/rmid \
            --slave /usr/bin/rmiregistry rmiregistry /usr/java/default/jre/bin/rmiregistry \
            --slave /usr/bin/servertool servertool /usr/java/default/jre/bin/servertool \
            --slave /usr/bin/tnameserv tnameserv /usr/java/default/jre/bin/tnameserv \
            --slave /usr/bin/unpack200 unpack200 /usr/java/default/jre/bin/unpack200
## configure alternatives for java
update-alternatives --install /usr/bin/javac javac /usr/java/default/bin/javac 16001 \
        --slave /usr/bin/appletviewer appletviewer /usr/java/default/bin/appletviewer \
        --slave /usr/bin/apt apt /usr/java/default/bin/apt \
        --slave /usr/bin/extcheck extcheck /usr/java/default/bin/extcheck \
        --slave /usr/bin/idlj idlj /usr/java/default/bin/idlj \
        --slave /usr/bin/jar jar /usr/java/default/bin/jar \
        --slave /usr/bin/jarsigner jarsigner /usr/java/default/bin/jarsigner \
        --slave /usr/bin/javadoc javadoc /usr/java/default/bin/javadoc \
        --slave /usr/bin/javah javah /usr/java/default/bin/javah \
        --slave /usr/bin/javap javap /usr/java/default/bin/javap \
        --slave /usr/bin/jconsole jconsole /usr/java/default/bin/jconsole \
        --slave /usr/bin/jdb jdb /usr/java/default/bin/jdb \
        --slave /usr/bin/jhat jhat /usr/java/default/bin/jhat \
        --slave /usr/bin/jinfo jinfo /usr/java/default/bin/jinfo \
        --slave /usr/bin/jmap jmap /usr/java/default/bin/jmap \
        --slave /usr/bin/jps jps /usr/java/default/bin/jps \
        --slave /usr/bin/jrunscript jrunscript /usr/java/default/bin/jrunscript \
        --slave /usr/bin/jsadebugd jsadebugd /usr/java/default/bin/jsadebugd \
        --slave /usr/bin/jstack jstack /usr/java/default/bin/jstack \
        --slave /usr/bin/jstat jstat /usr/java/default/bin/jstat \
        --slave /usr/bin/jstatd jstatd /usr/java/default/bin/jstatd \
        --slave /usr/bin/native2ascii native2ascii /usr/java/default/bin/native2ascii \
        --slave /usr/bin/policytool policytool /usr/java/default/bin/policytool \
        --slave /usr/bin/rmic rmic /usr/java/default/bin/rmic \
        --slave /usr/bin/schemagen schemagen /usr/java/default/bin/schemagen \
        --slave /usr/bin/serialver serialver /usr/java/default/bin/serialver \
        --slave /usr/bin/wsgen wsgen /usr/java/default/bin/wsgen \
        --slave /usr/bin/wsimport wsimport /usr/java/default/bin/wsimport \
        --slave /usr/bin/xjc xjc /usr/java/default/bin/xjc \
        --slave /usr/bin/jvisualvm jvisualvm /usr/java/default/bin/jvisualvm \
        --slave /usr/bin/HtmlConverter HtmlConverter /usr/java/default/bin/HtmlConverter

chkconfig puppet                  off
chkconfig atd                     off
chkconfig auditd                  off
chkconfig crond                   off
chkconfig cups                    off
chkconfig lvm2-monitor            off
chkconfig haldaemon               off
chkconfig portreserve             off
chkconfig postfix                 off
chkconfig messagebus              off
chkconfig nfslock                 off
chkconfig iptables                off
chkconfig ip6tables               off
chkconfig rpcbind                 off
chkconfig rpcgssd                 off
chkconfig hadoop-httpfs           off
chkconfig cloudera-scm-agent      off
chkconfig cloudera-scm-server     off
chkconfig cloudera-scm-server-db  off
chkconfig abrt-ccpp               off
chkconfig abrtd                   off
chkconfig cpuspeed                off
chkconfig dkms_autoinstaller      off
chkconfig irqbalance              off
chkconfig kdump                   off
chkconfig mdmonitor               off
chkconfig sysstat                 off
chkconfig vboxadd                 off
chkconfig vboxadd-service         off
chkconfig vboxadd-x11             off
## insert old vagrant ssh key
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" > /home/vagrant/.ssh/authorized_keys
## clean up unneed files
yum clean all
if [ -f /etc/yum.repos.d/local.repo ]; then rm /etc/yum.repos.d/local.repo; fi
