# -*- mode: ruby -*-
# vi: set ft=ruby :

# To DRY UP Vagrant File
# Reference: http://www.element84.com/dry-up-your-vagrant-files.html
NUM_BOXES = 2

Vagrant.configure("2") do |config|
  # use loop to generate multiple VMs with similar configurations
  (1..NUM_BOXES).each do |i|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.hostmanager.enabled = false
    config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
      if vm.id
      	`aws ec2 describe-instances --query 'Reservations[*].Instances[*].PrivateIpAddress' --instance-ids #{vm.id} --output text`.split()[0]
      end
    end
    config.vm.define "vm#{i}".to_sym do |vm1|
      vm1.vm.box       = "dummy"
      vm1.vm.box_url   = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
      vm1.ssh.username = "root"
      vm1.vm.provider :aws do |aws, override|
        aws.access_key_id     = ENV['AWS_ACCESS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET_KEY']
        aws.keypair_name      = ENV['AWS_KEYPAIR_NAME']
        aws.ami               = "ami-20b8a972"
        aws.region            = "ap-southeast-1"
        aws.instance_type     = "r3.large"
        aws.tags              = { "Name" => "vm#{i}" }
	override.ssh.username = "root"
	override.ssh.private_key_path = ENV['AWS_KEYPAIR_PATH']
      end
      vm1.vm.provision :hostmanager
    end
  end
end
